### ISSUE TITLE
As a user researcher, I want to conduct a user definition workshop with NSF so I can better prepare them and the team for future research work. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#10]
## User story
As a user researcher, I want to conduct a remote user research workshop with NSF so I can better prepare them and the team for future research work. 
  
## Acceptance criteria
- [x] An invite / brief to the remote workshop has been written that explains the value of the workshop.
- [x] An agenda is created
- [x]  Relevant OLPA and IDB staff should be identified and invited to the workshop. 
- [x] A date and time is selected.
- [x] A calendar invitation is sent 

### Workshop prep
- [x] Intro slides for workshop
- [x] Final agenda distributed
- [x] Supplies confirmed
- [x] Final slide deck complete

## Definition of done
- [x] The date, time and agenda are agreed to and scheduled.
- [x] The remote workshop is conducted.

**Comment by onezerojeremy** [comment]
Update: Due to the miracle scheduling ability of @openglobe, it seems like the remote workshop might be an in-person workshop after all. Here's a draft outline for an agenda! Please comment! 

https://docs.google.com/document/d/1zz9__xgEeBHvK32pcB3Lq9hZzbcUlPQp9P0i5gFrPkM/edit#

**Comment by onezerojeremy** [comment]
Adding a first crack at a deck: 
https://docs.google.com/presentation/d/1ssX2kwHAtzEohmSdgjYWQ0YndXaGeSI35dtzpEMWjhU/edit#slide=id.g24d021a1e7_0_57

**Comment by OpenGlobe** [comment]
Notes from standup: 

- let's add a bit more about the previous work, less about 18F in particular
- let's talk about expectation / level setting
