### ISSUE TITLE
Implement formatted preview for articles

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#101]
## User story
As someone editing an article, I want to be able to see a formatted preview so that I can verify the effects of my changes before saving.
  
## Acceptance criteria
- [x] Preview matches the layout of the Comb Jelly article

## Outstanding questions
- What's the layout of the Comb Jelly article?

**Comment by fureigh** [comment]
@RPentola, can you provide a link to the Comb Jelly article you mentioned? Thanks in advance!

**Comment by RPentola** [comment]
Hi @fureigh,

Chris put this on Slack when we were debating what to use for preview:

I put one of them on the wiki - https://extwiki.nsf.gov/display/18FCMS/User+Research%3A+CMS+Prototype

**Comment by RPentola** [comment]
Hi @fureigh 
Chris posted the links in slack (pasting below). I'd like a version of one of these to be what the user will see when they click "preview" (with their content inside the text area). I think #3 is probably the simplest, but please let me know. 

**Also, we don't need the preview to be in 100% fidelity with the mockup. We are on limited time, obviously! Let's chat about it at the meeting today.

these are the mocks of the content page that have more polish
v1 - https://gsa.invisionapp.com/share/2XDKYUKEU
v2 - https://gsa.invisionapp.com/share/TMDKYUUFW
v3 - https://gsa.invisionapp.com/share/5MDKYV92F

**Comment by RPentola** [comment]
Since we have what you need for the issue, I removed the "blocked" label.

**Comment by fureigh** [comment]
@RPentola Ready for review (ex: /news/comb-jellies-hold-key-deep-sea-evolution).

It's not currently at 100% fidelity, but it's a heck of a lot closer. Let's touch base about it later today and make follow-up tickets if/as necessary.

**Comment by RPentola** [comment]
We should discuss. I'm confused on the "view" and "preview" buttons and still think we should eliminate one of them.
