### ISSUE TITLE
As an author, I want content that is cut and paste to use the CMS default stylings. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#102]
# Current behavior
The pasted text appears to have different body fonts, but all user reports to see is “format” drop down with basic styles

# Desired behavior
Content that is cut and paste from another document matches system styles instead of retaining original formatting from document.

**Comment by fureigh** [comment]
I believe @peggyatnsf said in our daylong meeting that users shouldn't be able to choose different fonts or styles, just heading sizes, emphasis, etc. @peggyatnsf, can you confirm the desired behavior?

**Comment by peggyatnsf** [comment]
User should be able to choose from relevant styles in our stylesheet, along with things like bold, and italic. So no fonts, sizes or colors, but styles should be available.

**Comment by peggyatnsf** [comment]
Reading Robin's original issue, the text shouldn't retain the styling of the original document it is pasted from. It should be automatically converted to the default body style.

**Comment by OpenGlobe** [comment]
I updated this issue to better reflect the observed behavior.  Feel free to correct if it's still not quite right.

**Comment by fureigh** [comment]
@peggyatnsf Thanks! Can you give a few examples of styles?

**Comment by fureigh** [comment]
@OpenGlobe Hmm — the new description is an entirely different issue than the previous one and the previous one hasn't been preserved, so it's hard to compare for context. Can you paste the text of what @RPentola reported?

**Comment by peggyatnsf** [comment]
body text - Arial, 14px, #3c3d3e, 20px leading, 14px bottom margin on paragraphs
H1. Heading 1 (Georgia, 24px, #3c3d3e)
H2. Heading 2 (Arial Bold, 12px, #5b5954, uppercase, padding: 24px 0 8px 0; border-bottom: 3px solid #bcbdbe)

**Comment by fureigh** [comment]
@peggyatnsf Okay, perfect! Thanks. They can choose from `p`, `H1`, `H2`, etc. and those styles will be automatically applied (once the design is actually implemented).

**Comment by fureigh** [comment]
(Correction: here they're called `Normal`, `Heading 2`, `Heading 3`, etc.)
