### ISSUE TITLE
Certain functionality is unclear. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#105]
From the user: how do we envision this working? Does it solve an issue web content producers have? Or is it something we should turn off?

<img width="438" alt="screen shot 2018-01-26 at 1 04 51 pm" src="https://user-images.githubusercontent.com/5495118/35453798-86f9b850-0299-11e8-806c-fc76721c1103.png">

**Comment by fureigh** [comment]
@RPentola, can you help me understand which part you're referring to?

**Comment by RPentola** [comment]
Hi Fureigh, I was referring to the text format information (see arrows in attached image). 

It is not clear to me that this is needed. (The way it is supposed to work is also rather unclear.) I'm thinking this should not be part of what we show the content creator. Can it just be turned off?
Robin

![image](https://user-images.githubusercontent.com/31519450/35509573-abbdce76-04c2-11e8-81de-985a99a334fc.png)
