### ISSUE TITLE
Purpose of edit summary button is unclear. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#106]
## Current behavior
Summary button appears active when user hasn't created a summary. 

<img width="474" alt="screen shot 2018-01-26 at 1 14 44 pm" src="https://user-images.githubusercontent.com/5495118/35454161-ebdac894-029a-11e8-95bb-de2ed04f3334.png">

## Desired behavior
Summary button isn't active if user hasn't created a summary.

**Comment by fureigh** [comment]
LOE: tiny. If you don't need summaries, turning them off is very quick.

**Comment by fureigh** [comment]
It'd be possible to write something to conditionally say `Create summary` or `Edit summary` depending on whether that page didn't or did have summary content, but it sounds like there's no need for them in the current site.
