### ISSUE TITLE
Edits do not appear to be saved once view tab is pressed. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#107]
## Current behavior
Edits do not appear to be saved once view tab is pressed. 

## Desired behavior
Content is saved, or user is warned to save content prior to switching view.

**Comment by fureigh** [comment]
This functionality isn't built into Drupal core, so the next step would be to evaluate the available contributed modules, [Autosave Form](https://www.drupal.org/project/autosave_form) and [Save Form State](https://www.drupal.org/project/form_save_state).
