### ISSUE TITLE
Request to relabel "basic page" to "webpage" to better match terminology. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#108]
Request to relabel "basic page" to "webpage" to better match terminology. 

<img width="488" alt="screen shot 2018-01-26 at 1 22 14 pm" src="https://user-images.githubusercontent.com/5495118/35455413-c132060c-029f-11e8-8ebe-09362d28f810.png">

**Comment by fureigh** [comment]
Instead of changing it to just `page`, correct? Ready for review.

**Comment by OpenGlobe** [comment]
@rpentola reassigning you here.

**Comment by RPentola** [comment]
Looks good. thanks.
