### ISSUE TITLE
NSF network slowing access to the prototype

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#111]
## User story
As an NSF staff member evaluating and doing user testing on the prototype, I want the NSF network to allow unslowed access to the prototype so that I can reliably access the prototype during user testing without interference from slowdowns.
  
## Acceptance criteria
- [ ] The prototype reliably loads at regular speeds on the NSF network.

## Technical notes
- [ ] Could DIS whitelist the relevant IP address for the duration of user testing, at least?
- [ ] Test on multiple devices

**Comment by fureigh** [comment]
@mtboesch, you raised your hand for this one, correct?

**Comment by mtboesch** [comment]
What is the prototype URL again?

**Comment by fureigh** [comment]
Noting next step from email: @fureigh will follow up w/ host.

**Comment by fureigh** [comment]
Marking this closed, as this round of usability testing is complete.
