### ISSUE TITLE
Estimate a level of effort around the issues raised so far

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#112]
## Why
So we can decide what to prioritize for this round of user testing and what to capture for later.

## Acceptance criteria
- TK

**Comment by fureigh** [comment]
I'm adding notes on the relevant GitHub issues. For a more succinct version, see the `Estimated level of effort` column in [QA CMS webpage 1st round](https://docs.google.com/document/d/1ZkA4DQmTMu-INhjCq4_VGjznX7t-ONgIBkkG4KQYNOA/edit).

**Comment by OpenGlobe** [comment]
Sheet was updated - closing here.
