### ISSUE TITLE
User cannot determine title of article. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#114]
## Current behavior
"What is title? The file name? The H1 header? Looks like title is the filename. 
I can’t tell if it’s the H1 header on my webpage--the preview doesn’t help me see how it will display."

**Comment by fureigh** [comment]
@RPentola The `Title` field determines the name of the page (/article/etc.). When building the site, it's possible to configure where and how the title is displayed. By default it usually shows up in the title bar and as an H1 header at the top of the page.

**Comment by RPentola** [comment]
Hi All,

Do we want users to make their own page/file names? The “title” field will also be file name. Could we run into non-standard characters? Overly long title/file name? What do you think?

(This is for future consideration—doesn’t need to be in place for initial testing.)

Robin

**Comment by trinehar** [comment]
Here’s a typical title for a Dear Colleague Letter for a vacancy announcement:
Dear Colleague Letter: Chemical, Bioengineering, Environmental and Transport Systems (CBET), Directorate for Engineering (ENG) - Employment Opportunity for a Program Director Position overseeing the Process Separations Program (Open Until Filled)

Cutting and pasting from Word is common, and often breaks the RSS feeds when it happens.
