### ISSUE TITLE
Request to move the location of the moderation status box

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#115]
## Current behavior
the placement of the moderation status is not optimal--it breaks up page continuity. Can it be moved?  is it possible to move that up into the header?

<img width="452" alt="screen shot 2018-01-26 at 5 06 44 pm" src="https://user-images.githubusercontent.com/5495118/35462758-5a71be64-02bb-11e8-8b8c-bf6c65b4f8aa.png">

Move to: 

<img width="331" alt="screen shot 2018-01-26 at 5 06 49 pm" src="https://user-images.githubusercontent.com/5495118/35462755-55d71138-02bb-11e8-826e-6b7bd8aab540.png">

**Comment by fureigh** [comment]
LEO estimate: small to medium.
