### ISSUE TITLE
Feature request to change dropdown to button + pop-up

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#116]
## Current behavior

Instead of dropdown, can this be handled via a button → popup?  May prove more intuitive to click a button that says “send to review” with a popup “are you sure?” before sending-- as opposed to a dropdown.

Can test later, but want to know if this is a capability drupal can support.

<img width="452" alt="screen shot 2018-01-26 at 5 09 47 pm" src="https://user-images.githubusercontent.com/5495118/35462815-bb47b02c-02bb-11e8-91b7-2fd930c829f1.png">

**Comment by fureigh** [comment]
How about handling this with inline live form validation? The flow would be:
1. User clicks the `Change to` dropdown menu.
2. User selects their desired option.
3. If the option they selected is `Ready for review`, a message (presumably red) appears in close proximity to that field, saying something about the consequences.
4. If the user clicks `Apply`, their changes are immediately applied.

This approach would avoid the accessibility challenges of popup windows and the risk that the user could lose their work by clicking the `Apply` button and thinking they're done.

Either way, it's doable but would require a few lines of code.

But! The fact that users can now easily pull their content back from review may obviate the need for this. They essentially have an 'Undo' now for `Ready for review`, which they didn't before. My .02 would be to test _that_ functionality so the stakes are low. I hesitate to show an error when they're doing something they're routinely supposed to do.
