### ISSUE TITLE
As an author I want to be able to more easily link related pages and content. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#117]
## Current behavior

I want to link a subpage to my main AC page. Is there a way to pull a list of site pages and click (or drag) the one I want? 

It will be cumbersome to expect users to open page/copy URL/paste - is there a way to structure the CMS to allow a simpler way of linking related pages inside the nsf site?

**Comment by fureigh** [comment]
Yep! It's just a matter of configuring an Entity Reference. (And figuring out the details of which options should be surfaced, when and how and to whom.)

**Comment by fureigh** [comment]
In other words, level of effort: small.
