### ISSUE TITLE
As a site owner I want to verify that content meets accessibility guidelines

### ISSUE THREAD

**Issue by trinehar** [18F/nsf#118]
## User story
As a site owner / publisher, I want to verify that published content meets accessibility guidelines so that all users can navigate and obtain information and the site complies with federal regulations. 
  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
Thanks for including this, @trinehar! What acceptance criteria do you have in mind?

**Comment by fureigh** [comment]
For instance:
* [ ] HTML markdown complies with Section 508 guidelines
* [ ] All images have alt text
* [ ] ...

**Comment by trinehar** [comment]
All pages and content should comply with Section 508 guidelines.
Content publishers can check their pages before publishing.
I don't know whether modules like a11y and tenon can check uploaded files/attachments as well as generated content, but that would be helpful
