### ISSUE TITLE
unreadable menu items

### ISSUE THREAD

**Issue by RPentola** [18F/nsf#125]
## User story
As a content creator, I want a readable menu item so I don't have to squint/rollover it to read my options
  
![image](https://user-images.githubusercontent.com/31519450/35870976-0d2f63da-0b31-11e8-85bf-153cb41a37e4.png)

## Acceptance criteria
- [ black text ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
@RPentola Ready for review at `/node/add/news`:

<img width="557" alt="screen shot 2018-02-06 at 11 15 33 am" src="https://user-images.githubusercontent.com/1244599/35879003-ee363ffa-0b2e-11e8-8c6f-0821b9cd1580.png">

**Comment by RPentola** [comment]
looks good with black text.

**Comment by RPentola** [comment]
@fureigh not sure why this page is being created. We aren’t testing this with UX. Are you creating it for someone else?
