### ISSUE TITLE
Delete junk articles

### ISSUE THREAD

**Issue by RPentola** [18F/nsf#127]
## User story
As a user I want to see only articles that are meaningfully complete so that I am not distracted by junk/test articles.
  
![image](https://user-images.githubusercontent.com/31519450/35871098-61973b3c-0b31-11e8-9aba-569a9b6f8899.png)

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
@RPentola 👌  I've removed the dummy content in the `live-nsf` environment. I left the following articles in hopes of saving you time, but if you prefer, you can log in as your 'content admin' user and unpublish them:
  * /news/comb-jellies-hold-key-deep-sea-evolution
  * /news/illuminated-creatures-shallows
  * /news/test-article-new-layout

Alternately, if you'd rather I delete those entirely so you don't have to do the unpublishing, just @ me in Slack or here. Thanks!
