### ISSUE TITLE
Remove/concel cluttered text format instructions

### ISSUE THREAD

**Issue by RPentola** [18F/nsf#130]
## User story
As a content creator I want clean, non distracting information on my screen so that I may perform my main task quickly and intuitively. 
  
![image](https://user-images.githubusercontent.com/31519450/35871281-d8841a44-0b31-11e8-8f0d-1b7e55823c83.png)

## Acceptance criteria
- [hide or collapse ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
@RPentola Ready for review.

Technical notes: Closed in 28518278b04a98314cf5a9b37a648f88c0e9ce1e. Hid with CSS for now, for speed of implementation. For a production site, consider the [Better Formats](https://www.drupal.org/project/better_formats) module or a small custom module that uses the [Form API](https://api.drupal.org/api/drupal/core%21core.api.php/group/form_api/8.4.x) to omit that piece before rendering.

**Comment by RPentola** [comment]
looks fine. closing
