### ISSUE TITLE
Summary text editing area 

### ISSUE THREAD

**Issue by RPentola** [18F/nsf#131]
## User story
As a content creator, I want to perform my work in an environment that is easy to understand so I don't waste time trying to understand the interface.

*The alignment is super confusing. What am I doing? working on body or summary?
![image](https://user-images.githubusercontent.com/31519450/35871382-186b53b6-0b32-11e8-85f7-4ad4c0b6e9f3.png)

  
## Acceptance criteria
- [If feature useful for OLPA, leave it in --but expanded ]
- [If not useful--hide it. ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
@RPentola Ready for review. (Summary functionality is now removed from this field on articles as well as pages.)

**Comment by RPentola** [comment]
summary is removed.  Will check with OLPA later to see if it's something they need in future. Not needed for testing at this time.
