### ISSUE TITLE
Scheduling options are blank

### ISSUE THREAD

**Issue by RPentola** [18F/nsf#132]
## User story
As a content creator i want to be able to use a scheduling option (if presented) to schedule article publication.

This feature doesn't work. We also are not testing it in this round. Recommend hiding.
![image](https://user-images.githubusercontent.com/31519450/35871448-4c63aca4-0b32-11e8-9fa3-3faee7a5347f.png)

  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
@RPentola Ready for review.

### Technical notes in case of future reference:
This is a Firefox issue; date picker doesn't display until the user clicks in the field, and time doesn't show at all. Removed via permissions for now.

`scheduler` and `scheduler_rules_integration` are the relevant modules.

**Comment by RPentola** [comment]
good know. We'll have to decide if/how to implement so it works more seamlessly in supported browsers
