### ISSUE TITLE
View vs. preview buttons

### ISSUE THREAD

**Issue by RPentola** [18F/nsf#133]
## User story
As a user I want to have a single preview button that has the same behavior so that i can see what my article will look like when published.

There is a "view" and a "preview"  button with different behavior. Get rid of "view" make them both preview and with same behavior.

![image](https://user-images.githubusercontent.com/31519450/35871490-67c186ce-0b32-11e8-9cf1-0869b475e1ca.png)

  
## Acceptance criteria
- [preview option only ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
@RPentola Leaving this one as-is for now; ‘view’ displays the content as it is now (live on the site), whereas ‘preview’ displays the content as it will be if you save your edits. We can discuss further tomorrow if you'd like.

**Comment by RPentola** [comment]
I have a problem with this function.

What if you are creating the article new? Is it blank? We don't provide anything like "view" currently, and I'm not sure this is value added (as opposed to popping a separate window to see what's there now).

**Comment by RPentola** [comment]
Question for future testing/development. closing ticket.
