### ISSUE TITLE
background color change

### ISSUE THREAD

**Issue by RPentola** [18F/nsf#134]
## User story
As a user i want a unified presentation so i can work with minimal distraction. 
  
Change pink background to blue or grayscale. 

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
The changed background color (pink, by default) is an indicator that the page isn't published. It's meant to prevent people from thinking their pages are live when they're not. Let's discuss tomorrow.

**Comment by RPentola** [comment]
Not necessary for current testing. closing ticket
