### ISSUE TITLE
review feature doesn't work as intended

### ISSUE THREAD

**Issue by RPentola** [18F/nsf#135]
## User story
As a user i want to be able to control when my article is ready to review or in draft status so that it is not sent to my reviewer before it is ready. 
  
![image](https://user-images.githubusercontent.com/31519450/35871666-cde8a180-0b32-11e8-8f82-1fa8911b26d5.png)

It appeared to autosave it to ready-to-review. May need to test this more in the future.

## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
@RPentola I've been unable to replicate this; it works for me when logged in as a content editor (in Firefox as well as Chrome). Can you provide steps to reproduce this issue?
