### ISSUE TITLE
What are the options for having dev, UAT and production environments at cloud.gov

### ISSUE THREAD

**Issue by trinehar** [18F/nsf#141]
## User story
As a product owner I want to understand if and how cloud.gov can support pre-production (dev, UAT) environments as well as production environments. Are these considered "spaces" within a "system"?
  
## Acceptance criteria
Understanding is achieved

## Definition of done
Identification of any additional support needed to set this up at cloud.gov
Alternative ways to support dev/UAT/prod environments are proposed if only prod is at cloud.gov

**Comment by cmc333333** [comment]
You've got it, @trinehar, cloud.gov gives every "organization" three "spaces" by default: dev, staging, & prod. The names are just guidelines, however, we can add spaces or host production data in the "dev" space -- it's up to us to determine how to use the spaces.

Our cloud.gov quota has a cap on the amount of resources we can use (roughly translating to the total amount of RAM we can use), which we can allocate however we desire across our spaces. A solid approach (and the most common) is to have a nearly identical deployment between the "prod" and "dev" spaces, with some variation around server count and domain names. In this way, the "dev" space mirrors "prod", hosted at a different URL and with slightly fewer resources.

I think this approach would work just fine for us, and requires little-to-no additional configuration.

**Comment by trinehar** [comment]
Understanding is achieved!
