### ISSUE TITLE
Document a design for cloud.gov traffic to go through the NSF TIC

### ISSUE THREAD

**Issue by mtboesch** [18F/nsf#145]
## User story
As a technical team member, I want to understand and be able to share with NSF DIS how we are going to ensure that traffic to cloud.gov for NSF team members will go through the NSF TIC so that we can meet ATO requirements and ensure compliance.
  
## Definition of done
- [ ] Design is documented and configurations are identified
- [ ] Design reviewed by NSF DIS and they have no further questions

It has been suggested by the cloud.gov team that this can be done by using https://cloud.gov/docs/apps/experimental/restricting-users-to-trusted-ip-ranges/, but my understanding is that this functionality will not be available in production cloud.gov for at least another month or two, which is beyond our end of March date.  If we need to pursue other options that cloud.gov has to offer, we need to get these conversations going ASAP between cloud.gov tech team and the DIS infrastructure team.  At this point, I think all we have heard from cloud.gov is an option that does not fit our timeline.

**Comment by cmc333333** [comment]
Latest from cloud.gov folks on the timeline is "more than 1 month but fewer than 4 months".

**Comment by cmc333333** [comment]
Heads up that the IP restriction won't cover the entirety of cloud.gov actions on launch. These services will be excluded:
- logs.fr.cloud.gov (their Kibana instance for log review)
- doppler/loggregator (a separate logging service, built into their infrastructure)
- `cf ssh` (ssh-ing into a running instance)
- deployer accounts (for automated deploys from CI)

They'll implement support for those based in customer need.

**Comment by mtboesch** [comment]
Since we are moving off cloud.gov, this issue will be closed.
