### ISSUE TITLE
As a team member, I want determine a design direction for the beta social page so that we can implement a beta site quickly without established brand guidelines

### ISSUE THREAD

**Issue by austinhernandez** [18F/nsf#148]
## User story
As a team member, I want determine a design direction for the beta social page so that we can implement a beta site quickly without established brand guidelines.
  
## Acceptance criteria
- [x] Team talks about the pros and cons of a design directions (time, effort, scalability, etc)
  - Suggestion for two options: Option 1: use design from [NSF Seed Fund](https://seedfund.nsf.gov/styleguide/layouts). Option B: in house design team provides a header and footer.
- [x] Team comes to a consensus. 

## Definition of done
- [x]  Team consensus between NSF and 18F on direction.

**Comment by OpenGlobe** [comment]
First iteration will be per early designs per Austin's work, and following Fureigh's technical review.
