### ISSUE TITLE
As a team member, I need to have a high-level sense of the project timeline so I can plan my work.

### ISSUE THREAD

**Issue by coreycaitlin** [18F/nsf#15]
## User story
As a team member, I need to have a high-level sense of the project timeline so I can plan my work.
  
## Acceptance criteria
- [x] Broad schedule of goals and questions is drafted
- [x] Identify next round of workshop type(s) and dates, confirm availability with team and NSF

## Definition of done
- [x] Schedule is shared with team
- [x] Scheduled is provided to NSF
- [x] Potential scheduling risks and opportunities are identified

**Comment by OpenGlobe** [comment]
Moving this to ready - following review we can send on to NSF for comment.
