### ISSUE TITLE
As a member of the NSF team, I want to understand the process of switching the cloud.gov hosting plan over from prototype to FISMA low.

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#152]
## User story
By the end of this sprint we want to understand the process of switching the cloud.gov hosting plan over from prototype to FISMA low, and are updated on the length of the existing agreement and funding amount remaining, and a ballpark date on when we want to make that switch happen. 
  
## Acceptance criteria
- [x] Process identified; 
- [x] End of agreement / funds documented / shared with NSF;

## Definition of done
- [x] Ballpark date for switch is agreed to.

**Comment by cmc333333** [comment]
Okidoki, from the cloud.gov technical side, this "switch" would be more of a quota update, meaning very quick. We might also consider renaming the org (it's currently `nsf-prototyping`), but that's also a quick turn around.

From the policy side, @brittag would need to verify whether the current IAA would need to be modified (to add more funding) before approving the change. I believe those funds are already allocated, but the *next step* is to confirm the current IAA covers this cost. We'll need to modify it if not.

**Comment by cmc333333** [comment]
@brittag's confirmed that the current IAA covers this upgrade, estimated through June '18. To make the request formal, we need to send it to cloud-gov-support@gsa.gov to create an audit trail; the actual switchover will be quick.

Regarding when to ask for this, we'll need to transition before setting up a domain name and before hosting "production" data. I'd recommend making the switch at least a few weeks before the anticipated first release, but don't see a major downside to making it now.

For reference, the price jump is $5k per year.

**Comment by ominina** [comment]
@cmc333333 thanks for all of this! @OpenGlobe I think we should let NSF know we are making the switch before we make it. Do you anticipate they will need cloud.gov past June 2018? If so, we should create a price estimate for the amount of time they might need it, which @brittag would help us think through.

**Comment by peggyatnsf** [comment]
@cmc333333 @ominina I anticipate we will need cloud.gov past June. Would it be possible to get an estimate for how long the remaining fund we have on the IAA will last?

**Comment by ominina** [comment]
The remaining funds should last until June 2018 @peggyatnsf. The Cloud.gov cost after that will be based on length of time cloud.gov is needed and usage - @OpenGlobe do you know how long NSF might need cloud.gov past June 2018?

**Comment by peggyatnsf** [comment]
@ominina Perhaps until September 2018.

**Comment by ominina** [comment]
@brittag and I will estimate!

**Comment by OpenGlobe** [comment]
Per Slack discussion, we'll extend to 09/30/2018.

**Comment by OpenGlobe** [comment]
Request to switch from prototype to FISMA-low has been submitted.
