### ISSUE TITLE
Document plan for cloud.gov login using NSF ADFS authentication service

### ISSUE THREAD

**Issue by cmc333333** [18F/nsf#154]
## User story
As a technical team member, I want to understand and be able to share with NSF DIS how we are going to ensure that cloud.gov logins are authenticated against NSF's ADFS so that we can meet ATO requirements and ensure compliance.
  
## Acceptance criteria
- [ ] A strategy is designed and approved by project team
- [ ] Cloud.gov expects strategy to work
- [ ] Strategy is reviewed by NSF DIS
- [ ] Decision is documented
- [ ] Stretch goal: We'd tested integration in the staging environment

**Comment by cmc333333** [comment]
## Context
* https://login.fr.cloud.gov/saml/metadata contains the data that’ll eventually need to be put in NSF’s ADFS
* https://cloud.gov/docs/ops/federated-identity/ is written from the cloud.gov operator’s perspective, but does give a sense of the configuration process between cloud.gov and NSF. There’ll be a chunk of data NSF needs to give to cloud.gov, which might be worth prepping now
* Cloud.gov doesn’t have agency-facing docs on how this’ll be set up yet (i.e. what NSF needs to do), but they do recommend reviewing the same type of setup for zendesk: https://support.zendesk.com/hc/en-us/articles/203663886-Setting-up-single-sign-on-using-Active-Directory-with-ADFS-and-SAML-Professional-and-Enterprise- — setting it up for cloud.gov will be very similar

## Next Steps
1. The cloud.gov staging environment’s SAML metadata is at https://login.fr-stage.cloud.gov/saml/metadata . That can be configured in NSF’s UAT enviornment.
2. NSF then needs to provide three pieces of information to cloud.gov:
    1. their own SAML metadata file (either the XML or a url to that XML)
    1. a list of email domains users might have (i.e. nsf.gov, but maybe others)
    1. a logo image (to display on the login badges page)
3. With that data, Britta et al. can configure their side of the auth and deploy to staging.
4. We’ll test to confirm all is working.
5. We repeat, this time with prod.

Ball should now be in DIS' court.

**Comment by cmc333333** [comment]
Quick update that DIS and cloud.gov are testing this out now.

**Comment by mtboesch** [comment]
This was completed in March.
