### ISSUE TITLE
Receive DIS approval for the ATO-related documents. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#163]
## User story
Receive DIS approval for the ATO-related documents. 
  
## Acceptance criteria
- [x] Approval received. 
- [x] Discuss Jenkins / CI
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by mtboesch** [comment]
The SSR and PIA documents for beta.nsf.gov on cloud.gov were approved by the DIS Security and Policy team back in March.
