### ISSUE TITLE
Implement the beta on cloud.gov

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#165]
## User story
Implement the beta on cloud.gov
  
## Acceptance criteria
- [ ] Give access/admin rights on cloud.gov to designated NSF staff
- [ ] Walk through assigning permissions  
- [ ] Admin-level account determinations
- [ ] Build out all and train on all environments (dev, staging, prod)
- [ ] Documentation / demo on dev environment
- [x]  Switch cloud.gov package
- [x] Point to beta.nsf.gov
- [ ] Turn off uneccessary functionality, determine config, document, and remove unecessary parts of the codebase / config
- [ ] Switch config from active deployment to prod-ready (security, performance, etc.)

**Comment by OpenGlobe** [comment]
@cmc333333 are we ok to close out this card?  Or is it helpful to keep open?

**Comment by cmc333333** [comment]
I think we can close it. I'm not sure we've checked off all the boxes, but I think the bulk of it is complete.
