### ISSUE TITLE
As a team member, I'd like to have recruiting-email templates ready to go so I can start recruiting interviewees ASAP! 

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf#17]
## User story
As a member of the project team, I want recruiting email templates available so that I can start recruiting interviewees as quickly as possible (thereby saving time down the line). 
  
## Acceptance criteria
- [x] Draft initial invite email
- [x] Draft follow-up email for interested folks
- [x] Draft final pre-interview confirmation email (if necessary)

## Definition of done
- [x] Drafts of emails are written
- [x] Drafts are shared with team for feedback

**Comment by OpenGlobe** [comment]
Part of #9

**Comment by kategarklavs** [comment]
Hey all! I've modified the email templates from the NASA SBIR project:

https://docs.google.com/a/gsa.gov/document/d/17VZcqgPMoQg2-MR7CeWkztHOI2OUr6S61ga7KfmKT1w/edit?usp=sharing

And I just shared these in the channel for feedback. Happy to keep tinkering with these as the team sees fit 🎉

**Comment by kategarklavs** [comment]
Shared the templates doc with the team, and @OpenGlobe added an excellent informal template for reaching out to groups/orgs. 

This task is done, for now (though I'm happy to re-open it if folks feel the templates need additional rounds of edits).
