### ISSUE TITLE
As a user researcher, I want to set up a website recruitment test so that I can see if we can recruit users in real time from the website. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#19]
## User story
As a user researcher, I want to set up a website recruitment test so that I can see if we can recruit users in real time from the website. 
  
## Acceptance criteria
- [x]  Have conversation with NSF's website recruitment test provider
- [x] Schedule conversation with NSF website owners, website technical contact
- [x] Confirm availability of NSF folks, and make proper introductions (NSF)
- [x] Choose **pages** to target for recruitment
- [x] Finalize implementation details 
- [x] Follow up with NSF on where we are in terms of discussions with external users (s).  (When we do reach out via research plan, make sure to give NSF a head’s up!)

## Definition of done
- [x] Confirmed plan with NSF's website recruitment test provider
- [x] Conversation with involved parties on NSF is scheduled, and availability confirmed by NSF
- [x] Page for recruitment is selected
- [x] Implementation details finalized

**Comment by line47** [comment]
Pages we will target on NSF.gov

- URLs beginning with `nsf.gov/about/`
- URLs beginning with `nsf.gov/news/`
- URLs beginning with nsf.gov/crssprgm/reu/

**Comment by OpenGlobe** [comment]
@line47 are we ok to close this?

**Comment by line47** [comment]
I think we could, though I would want to track the actual launch of the recruiter on the live site. 
Maybe that's a separate issue though.
