### ISSUE TITLE
As an NSF member of this team, I want to join Github so I can participate in the issues as assigned. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#20]
## User story
As an NSF member of this team, I want to join Github so I can participate in the issues as assigned.
  
## Acceptance criteria
- [x] Get list of NSF users, and reach out to them
- [x] Invite NSF folks to GitHub project board 

## Definition of done
- [x] NSF team is invited
- [x] NSF team joins!

**Comment by line47** [comment]
I've sent an email to Peggy, Ellen and Theresa today with instruction on GitHub account creation
