### ISSUE TITLE
Shorten content from Tumbler blogposts on aggregator page

### ISSUE THREAD

**Issue by EYWeir** [18F/nsf#218]
## User story
As a social media lead, I want the aggregator page to use only a snippet (one or two sentences) of each Tumbler post with a Read More link, instead of the entire blogpost, so that the content is easier to scan and more people will check out the Tumbler blog.  
  
## Acceptance criteria
Tumbler items are shorter.
Link to Tumber for Read more
- [ ]
- [ ]

## Definition of done
- [ ] Changes made to aggregator page. 
- [ ]
- [ ]

**Comment by fureigh** [comment]
@EYWeir I believe this came up before; it's a matter of changing settings on the Tumblr side. Can you ask the social media lead to change the configuration of the RSS feeds (for both Tumblrs that are being pulled in)?

**Comment by fureigh** [comment]
That appears to have fixed it. If it hadn't, we could return to the [Feeds](http://drupal.org/project/feeds) module, which as of this month has an [alpha release](https://www.drupal.org/project/feeds/releases/8.x-3.0-alpha1).
