### ISSUE TITLE
Include videos from Tumbler

### ISSUE THREAD

**Issue by EYWeir** [18F/nsf#219]
## User story
As a social media lead, I want the aggregator to include videos when pulling in Tumbler content to that people will see that there's a video that's part of the blogpost.  
  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
Hmm, I thought we'd already fixed this one. I'll check whether the configuration settings carried over properly.

**Comment by fureigh** [comment]
@EYWeir Confirming, this is configured correctly on nsf-demo.

From `/admin/config/services/aggregator/settings`:

<img width="757" alt="screen shot 2018-04-13 at 4 46 01 pm" src="https://user-images.githubusercontent.com/1244599/38761648-5ce9627c-3f39-11e8-9ffe-ff19d5467d22.png">

Are you seeing this with a Tumblr post that's been pulled in? (In other words, is this a bug report?) If so, please provide a link or screenshot. Thanks!

**Comment by EYWeir** [comment]
There are Tumbler posts with videos not shown onthe  aggregator page. From Glorymar
See the attachment. All the ones in yellow have a video on top and are not showing. The ones in red, have a photo and 
![tumblr scnreenshot-aggregator](https://user-images.githubusercontent.com/31252304/38813194-54063cd2-415c-11e8-932a-53e61bf43b95.JPG)
isn’t showing either. http://nationalsciencefoundation.tumblr.com/

**Comment by fureigh** [comment]
@EYWeir Thanks for those materials! This is now ready for review [on staging](https://nsf-demo.app.cloud.gov/). (Fixed in #224.)

**Comment by fureigh** [comment]
<img width="1006" alt="tumblr-videos-on-staging" src="https://user-images.githubusercontent.com/1244599/38960956-20117a3e-431b-11e8-9520-3b413c1c71ec.png">

**Comment by fureigh** [comment]
Closed by #224. Thanks!
