### ISSUE TITLE
Link to NSF's Comment Policy

### ISSUE THREAD

**Issue by EYWeir** [18F/nsf#220]
## User story
As a lead for NSF social media, I want the aggregator page to include a link to NSF's Comment Policy, Disclaimer, Privacy and Copyright page (https://www.nsf.gov/social/policies.jsp) so that users will understand social media policies.  
  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by fureigh** [comment]
@EYWeir Okay! I'll add that to the links in this next-level footer block:

<img width="864" alt="screen shot 2018-04-13 at 10 21 35 am" src="https://user-images.githubusercontent.com/1244599/38748630-9c5fad66-3f03-11e8-877f-791a3a3a19b1.png">

**Comment by fureigh** [comment]
(^ That's a partial screenshot of the current nsf.gov site.)

**Comment by fureigh** [comment]
Capturing specifications from today's conversation:
 * The link should say `Social Media Policies` and go to https://www.nsf.gov/social/policies.jsp.
 * It's meant to display only on the aggregator page, so let's not add it to the footer menu.
 * Implementation note: add it to the relevant view.

**Comment by fureigh** [comment]
Ready for review in #221.
