### ISSUE TITLE
As someone interested in participating in the research, I want to learn about the research and leave my contact information. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#23]
## User story
As someone interested in participating in the research, I want to learn about the research and leave my contact information. 
  
## Acceptance criteria
- [x] There is a place I can go to learn more about the research
- [x] I can provide contact details for follow up easily 

## Definition of done
- [x] Content for page created
- [x] Form created
- [x] A page is designed
- [x] ATO 👍 
- [x] Page is launched

**Comment by kategarklavs** [comment]
Howdy all! I've got a draft content doc here:

https://docs.google.com/a/gsa.gov/document/d/1u9L0LW-52MxmYGs2VnJJtqa2v5kkkq5YocFIvNzo5G8/edit?usp=sharing

My thought was that this page would provide a super-brief description of our work + a link to the survey. Does that sound right @onezerojeremy @coreycaitlin?

**Comment by kategarklavs** [comment]
OK! Jeremy and Corey have offered feedback on the copy for the splash page (& said copy is ready to go). 

Next up: Creating the form.

**Comment by kategarklavs** [comment]
Also, I shared this content with @line47 earlier today 🎉

**Comment by line47** [comment]
I've added content which can be viewed here - https://federalist-proxy.app.cloud.gov/preview/18f/nsf/uswds-jekyll/ 

I wasn't sure if the bulleted list should be links or not so I just copied the content as it is in the doc

**Comment by kategarklavs** [comment]
A quick update! @line47 and I met just a bit ago to discuss, and I made some content updates to the original splash page copy.
