### ISSUE TITLE
BP: As a workshop attendee, I want to know what will be covered so I can decide if I need to attend or not. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#240]
## User story
BP: As a workshop attendee, I want to know what will be covered so I can decide if I need to attend or not. 

## Acceptance criteria
- [x] Workshop agenda is created and distributed
- [x]  Output from previous workshops where we’d be covering similar exercises

**Comment by kategarklavs** [comment]
I created the draft agenda & shared it with @OpenGlobe and @austinhernandez yesterday evening; this morning, I shared it with @jenniferthibault to get her feedback.

Chris and I are currently reviewing the agenda and making some edits!

**Comment by kategarklavs** [comment]
Update! Just sent the NSF team the draft workshop agenda and asked for their thoughts.

@OpenGlobe - I'm not totally sure about the second to-do in this issue (rather, not totally sure what it entails). Do you want me to identify potential areas of overlap between this workshop & previous ones? (This is covered a little bit in our draft agenda, but I can add clarity, if necessary.)

**Comment by kategarklavs** [comment]
Earlier this week, I sent over a weekly ship report from the previous phase of this project (said report included a photo of an affinity-mapping exercise that I believe Jeremy or Corey had led -- it appeared to be about primary audiences).
