### ISSUE TITLE
BP: New design advocates from NSF. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#241]
We want a list of design advocates to include in future meetings / workshops. 
  
## Acceptance criteria
- [x] Ellen to provide a list of people to include (in Slack instead of here is fine). 
- [x] Chris / team to add to standups and invite to workshops

**Comment by kategarklavs** [comment]
One quick update: During today's standup, Ellen let us know that NSF has internal design advocates, so we won't need to spend any time during the workshop identifying folks in this role.
