### ISSUE TITLE
BP: As a member of the team, I want to see the survey results so I can get a better sense of design direction fit. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#242]
## User story
BP: As a member of the team, I want to see the survey results so I can get a better sense of design direction fit. 
  
## Acceptance criteria
- [x] Email survey to IDB & OLPA by 5/15
- [x] Responses complete/closed by 5/17 (?)
- [x] Provide response data to team COB 5/17 (?)
- [x] Synthesize survey + interview data by … 5/18? (possibly 5/21)
- [x] Interviews are completed by 05/18

**Comment by kategarklavs** [comment]
Survey was distributed on 5/15, and we'll be getting responses later today!

**Comment by kategarklavs** [comment]
@RPentola Thank you! I'm taking a look now.

**Comment by kategarklavs** [comment]
Just updated this — all interviews were completed last week, and we discussed survey + interview data at our workshop earlier this week.
