### ISSUE TITLE
BP: As a member of the team, I want to attend the workshop and see the report-out from it so I can understand and contribute to the direction of the brand principles work. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#243]
## User story
As a member of the team, I want to attend the workshop and see the report-out from it so I can understand and contribute to the direction of the brand principles work. 
  
## Acceptance criteria
- [x]  Travel and logistics are complete. 
- [x] Workshops are conducted. 
- [x] Workshop synthesis is written up. 
- [x] Workshop synthesis is shared. 
- [x] Affinity mapping and other artifacts compiled and shared. 
- [x] Next steps as they pertain to brand principles are identified.

**Comment by kategarklavs** [comment]
After our sprint-planning meeting yesterday, I shared an updated version of the report out (with the full list of brainstormed brand principles) in the partners channel — going to move this to done!
