### ISSUE TITLE
BP: As a member of the team, I would like to have a first draft of brand principles so I can begin envisioning how they will apply to the site. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#246]
## User story
BP: As a member of the team, I would like to have a first draft of brand principles so I can begin envisioning how they will apply to the site. 
  
## Acceptance criteria
- [x] Review the draft principles generated during the workshop
- [x] Isolate key ideas from those draft principles and create a more formalized document
- [x] Share with NSF team for feedback
           - [ ] Identify any needed “next steps” and a plan to complete them if identified during the workshop

**Comment by kategarklavs** [comment]
Update on this issue: Today, I reviewed the principles generated by workshop participants and started a first draft of some more formalized ones. Just shared what I have so far with @austinhernandez, and we'll be pairing tomorrow to go over the draft 👍

**Comment by kategarklavs** [comment]
Update! Draft brand principles are written — we'll be sharing them with the team during today's demo (and can send them to the team, in doc format, after the demo).
