### ISSUE TITLE
BP: As a stakeholder, I want to understand the current state of the project so I can see how we are aligning to expectations. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#248]
## User story
BP: As a stakeholder, I want to understand the current state of the project so I can see how we are aligning to expectations. 
  
## Acceptance criteria
- [x] Align with Olesya and broader team on status of work / engagement, and progress of our tasks. (Chris / Olesya)
- [x] Set up a time to discuss with Olesya on burn rate and where we’re at. 
- [x] Confirm progress against what we said we’d do, and align to where we are currently and where we hope to be
- [x] Add names from Ellen to the meetings!

**Comment by ominina** [comment]
Chatted with chris on 6/1 about broader status of work - chris will pull olesya into scope convos as necessary. 

Olesya also sends a weekly email every friday that outlines the funds spent/available for both the brand principles and CMS acq support work

**Comment by OpenGlobe** [comment]
We've scheduled a broader project review with the team for early next week, so I'm closing this issue here.
