### ISSUE TITLE
As a NSF team member, I would like instructions for the afternoon workshop so that I can conduct the inventory. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#249]
## User story
As a NSF team member, I would like instructions for the afternoon workshop so that I can conduct the inventory. 

## Acceptance criteria
- [x] Provide instructions/guidance so NSF can conduct inventory (Kate, Ellen, Scott)
(Was going to be the afternoon workshop - so NSF would like to take this on.)

Note: In progress - translated an article into a worksheet, being reviewed by Scott, will be shared with NSF (in progress)

**Comment by kategarklavs** [comment]
This is also in progress! @line47 is going to take a look at the instructions I prepared — once I get edits from him, I'll clean up the doc and share it in the partners channel :)

**Comment by kategarklavs** [comment]
Moving this to done! I shared the instructions in the partner channel this morning.
