### ISSUE TITLE
As a team member, I'd like a list of next steps so that I can plan on how best to continue and build on the work after the engagement ends. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#252]
## User story
As a team member, I'd like a list of next steps so that I can plan on how best to continue and build on the work after the engagement ends. 

## Acceptance criteria
- [x] Begin assembling a list of next steps for NSF (this would be normally delivered at the end of the engagement, but let’s start the bullet-point list now)
- [x] Mapping business needs against user needs
- [x] User research related tasks

**Comment by kategarklavs** [comment]
Austin and I have started on this task (we've begun compiling a list of next steps, and we'll present some of these next steps at tomorrow's demo).

**Comment by kategarklavs** [comment]
@OpenGlobe A small update here — @austinhernandez and I will be meeting with @EYWeir tomorrow to discuss thoughts on a rollout plan and associated comms.

**Comment by kategarklavs** [comment]
@austinhernandez and @OpenGlobe - it seems like items referenced in this issue are now captured by other issues. Are we OK to close this?
