### ISSUE TITLE
As a team member, I want get more clarity on front-end scoping needs and onboarding so that we can start the next phase of our project.

### ISSUE THREAD

**Issue by austinhernandez** [18F/nsf#257]
## User story
As a team member, I want get more clarity on front-end scoping needs and onboarding so that we can start the next phase of our project.
  
## Acceptance criteria
- [x] Identify team member (probably @line47 )
- [x] Check in with Chris and Olesya re: FE availability 
- [x] Update NSF 

## Definition of done
- [x] Team member onboards contributes and helps scope our next phase!

**Comment by kategarklavs** [comment]
@austinhernandez I'm happy to take the lead on this issue! I'll provide another update after our meeting tomorrow with Scott.

**Comment by kategarklavs** [comment]
Update on this issue: Today, we met with @line47 to discuss the possibility of his joining the team for the next phase of work. Scott is interested in the opportunity, and was going to discuss it with his supervisor (he'll keep us posted). 

cc @austinhernandez @OpenGlobe
