### ISSUE TITLE
As a designer, I want to design the final direction after NSF delivers consolidated feedback so I can present the final design direction.

### ISSUE THREAD

**Issue by austinhernandez** [18F/nsf#258]
## User story
As a designer, I want to design the final direction after NSF delivers consolidated feedback so I can present the final design direction.
  
## Acceptance criteria
- [x] Incorporate feedback in thoughtful holistic design
- [x] List out changes from one version to another
- [x] Prepare the design in InVision for internal viewing
- [x] Include more design context and rationale for members of a larger audience
- [x] ! Make sure that we have a list of hypotheses (related to #253 )

## Definition of done
- [x] Design is complete and final mockups are in InVision
- [x] List of changes addressed are documented.
- [x] We have a list of hypotheses for further testing

**Comment by kategarklavs** [comment]
An update on this issue: Earlier this week, we got feedback on NSF on the two design directions. @austinhernandez has begun implementing some of the changes. Before we can finalize the design direction, however, we need to get more info from NSF on which of the two directions they prefer.

Earlier today, we shared our draft Design Hypothesis Guide with NSF (and they'll be sending us feedback on it shortly)!
