### ISSUE TITLE
As an executive stakeholder, I want to have a short and pithy deck to educate senior leadership so I can get buy-in from the leadership team

### ISSUE THREAD

**Issue by austinhernandez** [18F/nsf#259]
## User story
As an executive stakeholder, I want to have a short and pithy deck to educate senior leadership so I can get buy-in from the leadership team. (Related to #256 )
  
## Acceptance criteria
- [x] Shortened version of #256 with no more than 25 slides
- [x] Share with NSF for feedback
- [x] Update the deck per NSF feedback
- [x] Deliver
- [Kate's deck outline here](https://docs.google.com/document/d/1-pOfjC7pS2zlNDxov7RJl23V7c_ZBujNtY6kL5k7bOw/edit)

## Definition of done
- [ ] [Condensed version](https://docs.google.com/presentation/d/1Kl8VERxwJ3LnjZJmWZb2taRVCIE0a8hrClgRZYB4NvY/edit#slide=id.g3b2e2a3af9_0_347) of the deck is complete and NSF team has no further updates

**Comment by austinhernandez** [comment]
Ready 4 tomorrow's demo and feedback

**Comment by kategarklavs** [comment]
Update: Still waiting for feedback on the short version of the deck. @austinhernandez and I have been working on the expanded version of the deck (editing slides, writing presenter notes, etc.).

**Comment by kategarklavs** [comment]
Per today's sprint planning meeting, we'll continue working on this task during this sprint.

**Comment by austinhernandez** [comment]
incorporating feedback from this doc: [Pitch deck for Amanda_Comments.docx](https://github.com/18F/nsf/files/2275916/Pitch.deck.for.Amanda_Comments.docx)

[Revised deck:](https://docs.google.com/presentation/d/1Kl8VERxwJ3LnjZJmWZb2taRVCIE0a8hrClgRZYB4NvY/edit#slide=id.g40153241f4_0_818)

**Comment by kategarklavs** [comment]
Deck has been shared! Going to hold off on moving this to "Done" until we make sure that NSF doesn't have any other questions.
