### ISSUE TITLE
As a team member, I want to kickoff for second phase of work so that we can come to alignment on what we’ll get done this engagement

### ISSUE THREAD

**Issue by austinhernandez** [18F/nsf#266]
## User story
As a team member, I want to kickoff for second phase of work so that we can come to alignment on what we’ll get done this engagement
  
## Acceptance criteria
- [x] NSF Brand Principles (Re)kickoff scheduled for Tuesday, August 7 12:30 – 1:30pm EST
- [x] Come to alignment on what we’ll get done
- [x] Share out results (report out)

## Definition of done
- [x] Share out results

**Comment by kategarklavs** [comment]
Shared the report out in the NSF partners channel — moving this to done! 🎉
