### ISSUE TITLE
As a designer, I want to wrap up brand principles implementation guide so I can present the final design direction.

### ISSUE THREAD

**Issue by austinhernandez** [18F/nsf#267]
## User story
As a designer, I want to wrap up [brand principles implementation guide](https://docs.google.com/document/d/1ex0O17yqbxKSFxp10P6e_w2Br9JKQbVTcVN_y7ksGR8/edit#heading=h.lfudhblzyynz) so I can present the final design direction.
  
## Acceptance criteria
- [x] Make final edits
- [x] Final check with internal team

## Definition of done
- [x] Deliver to NSF team

**Comment by kategarklavs** [comment]
Update! I made Ellen's recommended edits today — updated version of the guide is here:

https://docs.google.com/document/d/1T7KUMC0hOiuiWAZOGTUmzHNq79g3t4-2o-3PEhVxfgI/edit?usp=sharing

@austinhernandez & @micahtaylor, this is ready for your review 😌
