### ISSUE TITLE
As an NSF employee, I am interested in editorial-planning recommendations (and, more broadly, editorial strategies) so that I can understand how they might impact an eventual CMS / future web presence. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#27]
## User story
As an NSF employee, I want more information about different (& pertinent) editorial strategies so that I can understand how they might impact a CMS decision/NSF's future web presence. 
  
## Acceptance criteria
- [x] Complete list of NSF content types/observations
- [x] Get answers to questions related to various content types
- [x] Compile a list of best practices for editorial planning 
- [x] Likewise, compile a list of awesome editorial practices w/r/t individual pieces/various content types
- [x] Examine why these best practices are successful and relate them to NSF's work

## Definition of done
- [x] Document exists in team folder
- [x] Share recommendations doc with 18F team for feedback
- [ ] Distribute to NSF 
- [ ] Identify next steps!

**Comment by kategarklavs** [comment]
Howdy, all! Here's my update for today. First, I wanted to share a content-planning best-practices notes doc I'm working in:

https://docs.google.com/a/gsa.gov/document/d/1YtL9d7sq3RwTHfkSaRIZJsWNqU9xoCjC9qojYejzXXo/edit?usp=sharing

This isn't finalized yet, but it does contain some practices we can think about re: NSF's content strategy and editorial planning. I emailed Glorymar to get a copy of NSF's social media plan (waiting to hear back), and I also emailed Ellen to see if I could get ahold of their editorial-planning docs; Ellen will forward those once she has them.

I'm also gathering information about specific **content types** and am compiling my observations in this document (which is also still in progress):

https://docs.google.com/a/gsa.gov/document/d/1ThUHsVEhE6CGgv7UA5BvgQAbVE1h-yFGmziedFyKDiU/edit?usp=sharing

Once I have a good, solid draft of the content-types doc, I'll circulate it among the team for feedback.

**Comment by kategarklavs** [comment]
Howdy, all! Not too much to report today — I made more progress on the content types doc (which is nearing completion). 

I still haven't gotten any word from Glorymar re: NSF's social media strategy; I'll reach out to her tomorrow morning if I haven't gotten a response to my previous email.

**Comment by kategarklavs** [comment]
Update: Just emailed Glorymar again (never heard back after my initial email of 8/23).

**Comment by kategarklavs** [comment]
Another update! This morning, I started consolidating my content-related questions in this document:

https://docs.google.com/a/gsa.gov/document/d/1t-KOEHbyGzwNLu4NMbHHwGKJOQ-_a6T6rfECyP1VFMQ/edit?usp=sharing

My plan is to schedule some time with Ellen to discuss these questions/get answers (or, if necessary, get answers via email).

**Comment by kategarklavs** [comment]
I mentioned this in issue #39, but want to cross-post here: I chatted with Trinka and Laurie this week about Science 360, and I'm waiting to hear back from Rob/Glorymar about editorial calendars and NSF's Twitter/Medium accounts, respectively — hoping that we can set up calls for next week so I can close out this portion of the content research.

**Comment by kategarklavs** [comment]
An update here: Chatted yesterday (9/26) with Rob about editorial calendars. Am still trying to schedule a chat with Glorymar (and am moving forward with recommendations in the meantime).

**Comment by OpenGlobe** [comment]
In progress per standup on 10/03

**Comment by kategarklavs** [comment]
Update on this issue: I've been drafting editorial and content-strategy recommendations in the draft doc @line47 set up, and my plan for this week is to continuing editing these recs so that they're in more narrative form (as opposed to outline form). 

These recommendations will be part of our final report/list of recs. I never heard back from Glorymar and will write the social-media-focused recs based on established best practices/my experience on other projects.

**Comment by kategarklavs** [comment]
Per standup on 10/11, I'll add outstanding tasks to a new issue that encompasses the work we're doing for our final deliverable (CMS + content strategy recs).
