### ISSUE TITLE
As a user researcher, I want to know when outreach to lists is successful so I can plan on a new release to the next listserv on the priority list. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#33]
## User story
As a user researcher, I want to know when outreach to lists is successful so I can plan on a new release to the next listserv on the priority list. 

## Acceptance criteria
- [x] Users for a given list are contacted, and recruitment catches up with responses
- [x] An outreach list exists
- [x] Given that recruitment is happening via Twitter, web recruiter and listservs, a tally of our user types is kept so we know which ones need additional outreach

## Definition of done
- [x] NSF is contacted when each recruitment effort is finished for any given list.

**Comment by onezerojeremy** [comment]
outreach has been completed to all except Science Nation.

**Comment by OpenGlobe** [comment]
Added item per sprint planning.
