### ISSUE TITLE
As someone responsible for the web recruiter, I want to confirm the recruiter is set up and working properly so I can deploy it on more pages. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#34]
## User story
As someone responsible for the web recruiter, I want to confirm the recruiter is set up and working properly so I can deploy it on more pages. 
  
## Acceptance criteria
- [x] The web recruiter exists and is avaiable on NSF.gov
- [x] The form is set up and working properly
- [x] Recruiter appears to be wired correctly

## Definition of done
- [x] Team confirms web recruiter is reviewed and is working correctly
- [x] Recruiter is deployed on correct pages off NSF.gov domain

**Comment by onezerojeremy** [comment]
In reference to @line47's request to take a look at the recruiter here:

tab example - https://www.demo.nsf.gov/news/
button example - https://www.demo.nsf.gov/web-design-labs/
linked Google sheet - https://docs.google.com/spreadsheets/d/1tcetjs4QSdItTdLdAOeZl7w0fwg_DD0ri2bKNLybTBg/edit#gid=0


small tweaks I found:
1. the screener pop-up should read (45 minutes sounds scary long, and we may not need 45 with everyone): 
Thanks for offering to help us improve NSF.gov! Share your contact information below — if you’re selected, we’ll contact you to set up a **30-45 minute** conversation with a member of our team.

2. the button version doesn't look very button-esque. at a minimum, it needs a bit (say, twice what it has) more bottom padding/margin it. It might also be that we could use shorter text for a call to action. Paging @coreycaitlin and @kategarklavs on that, though. 😁

**Comment by line47** [comment]
Thanks @onezerojeremy ! I've made the text update to the modal. 

I'll work with the NSF folks to update the classes on that button page.

**Comment by kategarklavs** [comment]
@onezerojeremy I agree that the button text could be way shorter. How do you all feel about this?

Ì'll help out`

OR

`I'd like to chat``

(In other words, something short & conversational.)

Also, heading ("Help NSF Better Serve You") should be sentence case! I'll get that taken care of ...

**Comment by kategarklavs** [comment]
Update! Just checked in with @line47, and I'll need to get someone from NSF to update the capitalization 👍

**Comment by onezerojeremy** [comment]
Ohhhh I like  `I'd like to chat` a lot! 

(I worry that people might think they are signing up for marketing communications with "sign me up")

**Comment by kategarklavs** [comment]
@onezerojeremy Awesome! Let's go with `I'd like to chat`, then :)

**Comment by kategarklavs** [comment]
Just opened a PR to update the button text.
