### ISSUE TITLE
As someone responsible for the web recruiter, I want to confirm the recruiter is set up and working properly on Science360.gov

### ISSUE THREAD

**Issue by line47** [18F/nsf#38]
## User story
As someone responsible for the web recruiter, I want to confirm the recruiter is set up and working properly so I can deploy it on more pages. 
  
## Functionality 
- The user to clicks the tab "Help improve this site" in the lower right of the page on Science360 
- Upon clicking the tab the user would be taken to the web-design-labs page of NSF https://www.nsf.gov/web-design-labs/
- Once on the https://www.nsf.gov/web-design-labs/ page the user could click the button "I'd like to chat" to complete the form

### Pages/URLs to deploy on:
https://news.science360.gov/
https://science360.gov/radio/
https://science360.gov/files/

## Acceptance criteria
- [x] The web recruiter exists and is available on Science360.gov
- [x] The form is set up and working properly
- [x] Recruiter appears to be wired correctly

## Definition of done
- [ ] Team confirms web recruiter is reviewed and is working correctly
- [ ] Recruiter is deployed on correct pages off Science360.gov domain

**Comment by line47** [comment]
The recruiter is up and capturing data! There is one small issue to fix and than is with the learn more link. https://github.com/GSA/recruiter/issues/33

**Comment by OpenGlobe** [comment]
In progress per standup on 10/03

**Comment by laurenancona** [comment]
[GSA/recruiter#33](https://github.com/GSA/recruiter/issues/33) is resolved
