### ISSUE TITLE
As a content designer, I want to develop a better understanding of NSF's content types and editorial plan so I can make more informed recommendations going forward 

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf#39]
## User story
As a content designer, I want to develop a more in-depth understanding of NSF's content types, editorial calendar, and social media strategy so I can integrate this information into content strategy recommendations. 
  
## Acceptance criteria
- [x] Complete list of NSF content types/observations
- [x] Review NSF's editorial calendar 
- [x] Review NSF's social media plan
- [x] Get answers to outstanding questions

## Definition of done
- [x] Share content types document with team 
- [x] Review editorial calendar
- [x] Review social media strategy doc
- [x] Send questions to NSF

**Comment by kategarklavs** [comment]
Update! I sent my list of questions to NSF last week (Friday), and I heard from Ellen today that she'll get in touch with the folks at OLPA. Meanwhile, I'll meet with Corey to go over the list of questions/make sure I'm not duplicating any of her previous efforts. (I did review the contents of the "From NSF" folder (FE Drive Folder) today, and I didn't identify any major duplications, but I'll be happy to touch base with Corey nonetheless.)

cc @OpenGlobe

**Comment by OpenGlobe** [comment]
Sounds great @kategarklavs !

**Comment by kategarklavs** [comment]
Update on this issue: While in DC this week, I chatted with Trinka and Laurie about Science 360, and I'm waiting to talk to Rob and Glorymar about editorial calendars and Twitter/Medium, respectively. 

On the topic of the content-types doc, all that's left to do is for me to run through it and clean it up a bit — Rob had mentioned that he was interested in seeing it, and I'd like to do a final scan of it before sharing externally.

**Comment by kategarklavs** [comment]
Howdy, all! An update: Today, I chatted with Rob about NSF's editorial calendar/strategies for standardizing content workflows. I'm still waiting to hear back from Glorymar about when she can meet this week. Being that I've developed a solid knowledge of NSF's content types and editorial strategy, I'm going to close this issue.
