### ISSUE TITLE
As an attendee of the recent mid-point workshops, I'd like a summary of what we learned so that I can understand our next steps and how they apply to me. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#45]
## User story
As an attendee of the recent mid-point workshops, I'd like a summary of what we learned so that I can understand our next steps and how they apply to me. 
  
## Acceptance criteria
- [x] Given that the workshops are completed, and
- [x] We have a list of next steps, 
- [x] a written report will help the team document and track our progress against our goals. 

## Definition of done
- [x] Write-up of findings is completed
- [x] Write-up is delivered to NSF for comment / feedback

**Comment by kategarklavs** [comment]
@OpenGlobe Howdy! Checking in now with @coreycaitlin and will be sending this later today (I hope — will update the issue as soon as I send this over).

**Comment by kategarklavs** [comment]
Hello all! @coreycaitlin and I did a final sweep of the midpoint workshop report out yesterday and sent it to the NSF team. Closing this issue!
