### ISSUE TITLE
As a user researcher, I want to continue scheduling interviews for hypothesis #1 so that I can be prepared to test our first prototype(s). 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#46]
## User story
As a user researcher, I want to begin scheduling interviews for week 2 of this sprint so that I can be prepared to test our first prototype(s). 
  
## Acceptance criteria
- [x] We have individuals identified for user research; and 
- [x] We have a prototype ready to test; and
- [x] We have modified our research plan accordingly. 

## Definition of done
- [x] Individuals are contacted and interviews are scheduled.

**Comment by onezerojeremy** [comment]
@OpenGlobe can you run (or delegate) recruiting this week – I don't think I'll have capacity.

**Comment by onezerojeremy** [comment]
adding a list of subtasks for this:
- [ ] block some times (or a large chunk of time for appointment slots) on the team members calendars to hold for interviews
- [ ] contact the individuals who have left their information in the recruiter, sending an email asking if they are available to chat on Friday, sending them the self-scheduling calendar or a couple options for times
- [ ] follow up with them, confirm times and send them the participant agreement to sign ahead of their chat. 
- [ ] record scheduling, agreed on times, etc in tracking doc
- [ ] coordinate with team on when interviews are scheduled
- [ ] coordinate with Ellen to send out the pre-written tweet asking for participation either early this week or early next


below i'm including some adaptable template email language we used for the first round of recruiting: 
initial outreach:
> Hi XXX! 
> I saw that you filled out our sign-up form on the National Science Foundation web site indicating you'd be willing to chat about science news! Thanks so much, the team and I really appreciate it! 
> What does your Thursday look like? I'd love to schedule you for a quick 30-45 minute phone call or video chat, if you're willing. Take a look at this calendar and select any of the slots that work for you; if none of the times work (or if they are all gone), totally understandable; we can try for next week too. Also, if you can't see the calendar let me know that too and I'll send you some options manually.
