### ISSUE TITLE
As a team member, I need to know what the first hypothesis is so that I can start developing a prototype to test. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#47]
## User story
As a team member, I need to know what the first hypothesis is so that I can start developing a prototype to test. 
  
## Problem Statement
We believe that people interested in science information and news do not visit NSF.gov on their own.  We suggest that by making science information and news more discoverable through the channels they are already using, and written in a way that is more appealing to a broader audience, we can increase the visibility of NSF.gov amongst a wider range of individuals interested in science news and information. 

## Hypothesis #1 

Option 1: Improving the article page [page icon in Mural]  
We believe that **improving the website experience for users who reach articles from social media** will result in **more engaged readers who are interested in pursuing further information about NSF**.  We will know this is true when we see **users click on other articles, pursue related resources, or subscribe to similar news.**

- How related content is displayed
- Other articles
- Further reading/deeper dive for reporters and science learners
- See the research sidebar
- Calls to action for RSS feeds or other subscriptions
- Page element tying article to NSF mission (“how NSF makes this possible”)
- Summary/tl;dr — top level points for science communicators
- Connection information
- Entry point for people who want to reshare them
- Better multimedia

## Candidates:
https://www.nsf.gov/discoveries/disc_summ.jsp?cntn_id=242898&org=NSF&from=news
https://www.nsf.gov/discoveries/disc_summ.jsp?cntn_id=242850&org=NSF&from=news
https://www.nsf.gov/discoveries/disc_summ.jsp?cntn_id=243064&org=NSF&from=news
https://www.nsf.gov/news/news_summ.jsp?cntn_id=243121&org=NSF&from=news 

## Acceptance criteria
- [x] First hypothesis is identified and agreed to; and
- [x] Ideas around the hypothesis are sufficiently developed enough to allow us to start developing the prototype; 
- [x] Content type is selected (news page?  topic page? article page? jellys article?)
- [x] Calls to action for subscription
- [x] An NSF person is identified as the lead on the article page;
- [x] If someone would share what they find; 
- [x] Statement that explains the deeper connection to NSF, and further reading;
- [x] Tweets are written;
- [x] Page is redesigned (but still complimentary to the existing NSF page); 
- [x] Page is launched on Federalist;
- [x] We have rewritten the content; and
- [x] We can conduct moderated user testing. 

## Definition of done
- [x]  The first iteration of the first prototype is complete and published

**Comment by OpenGlobe** [comment]
@kategarklavs does the jellyfish article make a good candidate for this?

**Comment by kategarklavs** [comment]
@OpenGlobe Yes! I think the Comb Jellies article is a good one to prototype. Alternatively, if we're trying to target folks who are into super-timely science news, we could use a newer article (one that was just just published).

**Comment by OpenGlobe** [comment]
@austinhernandez there's a bit more framing information for that first hypothesis here...
