### ISSUE TITLE
As a team member, I want a prototype strategy so that I understand how we will gain understandings from tests that will drive recommendations 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#49]
## User story
As a team member, I want a prototype strategy so that I understand how we will gain understandings from tests that will drive recommendations. 
  
## Acceptance criteria
- [x] we have a research / hypothesis workflow identified; 
- [ ]

## Definition of done
- [x] A strategy is documented
- [ ]
- [ ]

**Comment by austinhernandez** [comment]
As we develop our our hypotheses here is one potential user flow (Twitter to article page to category/topic page): https://gsa.invisionapp.com/share/BECWK1ZT4#/256313865_2017-10-02-16-46-Twitter-com

**Comment by OpenGlobe** [comment]
Update: In progress per standup on 10/03
