### ISSUE TITLE
As someone working on the NSF project, I need to know where the initial in-person meeting will be that I can plan on attending.

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#6]
## User story
As a someone working on the NSF project, I need to know when and where the kickoff meeting will be that I can plan on attending.

## Acceptance criteria
- [x] A date and time for the kickoff meeting is selected and scheduled
- [x] A calendar invitation is sent to the rest of the team
- [ ] ~An agenda is developed for the kickoff meeting~
- [ ] ~Room / location is scheduled~
- [ ] Travel requests are submitted

## Definition of done
- [ ] The team accepts the meeting invitation
- [ ] The NSF accepts the meeting invitation
- [ ] ~NSF approves the agenda~
- [ ] Travel is approved

**Comment by coreycaitlin** [comment]
We've decided that the initial meeting can be partial (just Jeremy and maybe me), and we can plan a whole-team trip for later in the project when schedules line up better.

**Comment by coreycaitlin** [comment]
Our initial in-person meeting will overlap with #10, so I'm crossing out a few action items here that are better tracked in that issue.

**Comment by OpenGlobe** [comment]
I'm closing this, it's really a duplicated of #10 as noted.   We can open a separate card for follow-on workshop related activities.
