### ISSUE TITLE
As an NSF team member, I'd like high-level strategy recommendations to implement in conjunction w/the new CMS 

### ISSUE THREAD

**Issue by kategarklavs** [18F/nsf#64]
## User story
As a member of the NSF team, I'd like some high-level strategy recommendations that I can implement to continue improving the direction for NSF users. These strategies may (or may not) be directly tied to CMS recommendations; however, the CMS recs + these recs combined will result in a better experience for NSF.gov users.

Also of note: This issue refers to the end-of-project content deliverable.
  
## Acceptance criteria
- [x] Finish drafting NSF recommendations document
- [x] Edit all of the recs so they're in a more narrative format
- [x] Share out with 18F team for feedback
- [x] Full edit of entire recs doc (clarity, voice/tone, general copy edits)
- [x] CMS considerations, including rough estimates of the amount of lift required for various functionality (L) (Fureigh, Scott, Kate et al)
- [x] Format for presentation to NSF
- [x] Deliver to NSF.

## Additional documents
- [x] Recommendations include a CMS matrix document
- [x] CMS prioritized features document 
- [ ] Updated roadmap document

## Definition of done
- [x] Recs approved by 18F team. 
- [x] Document identifies concrete content strategies, visual design directions, and relevant research and CMS items
- [x] In person CMS workshop is scheduled

**Comment by fureigh** [comment]
I suggest we bundle the CMS considerations into the CMS prioritized features document. 🆒?
