### ISSUE TITLE
Cloud.gov prototype: As a team member, I want to understand what the MVP should look like so that I can begin understanding workflow needs as they pertain to any CMS decision. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#69]
## User story
As a team member, I want to understand what the MVP should look like so that I can begin understanding workflow needs as they pertain to any CMS decision. 

As a user researcher, I want access to the prototype so that I can develop tasks for the user research. 
  
## Acceptance criteria
- [ ] Given that I need access to the prototype, and
- [ ] the prototype is working in a cloud environment, 
- [ ] I should have access to something that allows me to develop the tasks for the user research.

## Definition of done
- [x] Site is stood up in a hosted environment
- [x] Share the latest version of the prototype into an NSF-accessible environment (i.e., up on cloud.gov). 

Developing the content editor workflow: 
- [x] Create news article
- [x] Find/navigate content (especially to edit)
- [x] Edit own content
- [x] Check on status of submitted content
- [x] Stretch: workflow: accept/reject

Central issue: reduce cruft and unnecessary options in the interface
Ideally, implement the visual guidelines/USWDS

Options for backup plans
- [ ] Setting up a local install on an NSF machine
- [ ] Interactive screenshare with screen (and audio) recording (less preferable)

**If by EOW (01/05/2018), we’ll use a local install to test the user research plan.**

**Comment by OpenGlobe** [comment]
Hi @fureigh !  Do you mind updating this issue when you have a free moment?  I think a few of these items are now complete?

**Comment by OpenGlobe** [comment]
Update per Fureigh: troubleshooting 2FA issues with cloud.gov install.

**Comment by fureigh** [comment]
*deployment issues. No 2FA issues yet, nor do I anticipate any. 🤞

**Comment by fureigh** [comment]
The above functionality — including the ability to find, edit and check the status of content — is in for an editor's own content. Some improvements could be made to their ability to find and check the status of others' content. I'll make follow-up tickets to capture those pieces.
