### ISSUE TITLE
As a team member, I want a platform that allows me to rapidly prototype HTML ideas. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#7]
## User story
As a team member, I want a platform that allows me to rapidly prototype ideas. 

## Acceptance criteria
- [x] Platform is selected that allows quick prototyping from a Github repository
- [x] Platform is set up 
- [x] Rights are granted for relevant team members

## Definition of done
- [ ] The platform is selected, presented and accepted by the team members
- [ ] Access instructions are provided to relevant team members

**Comment by line47** [comment]
Federalist is setup and working and I have set up a USWDS demo site as a test.
https://federalist-proxy.app.cloud.gov/preview/18f/nsf/uswds-jekyll/
