### ISSUE TITLE
As a CMS administrator, I want roles so that I can assign them to my users. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#74]
## User story
As a CMS administrator, I want roles so that I can assign them to my users. 
  
## Acceptance criteria
- [ ] User roles are identified
- [ ]
- [ ]

## Definition of done
- [ ] User roles are assigned, developed and available in the CMS. 
- [ ]
- [ ]

**Comment by fureigh** [comment]
The prototype currently includes content editor, content admin and site admin roles. From https://github.com/18F/nsf/issues/70 it appears that we'll want the following:
* [ ] WIG content editor
* [ ] WIG content admin
* [ ] OLPA content editor
* [ ] OLPA content admin
* [ ] Site admin

@RPentola, does the above sound correct to you? What permissions/responsibilities do NSF webmasters have?

**Comment by RPentola** [comment]
@fureigh Currently the webmasters have roles outside the actual systems. I would assume that going forward, working in a CMS, they would need author and editor access.

What do we mean by admin? Creating/dropping users? There's a possibility that role would be devolved down to the webmasters. Currently they don't have this kind of control.

As far as creating/changing site layouts (as an admin) -- I don't know if this would go to the webmasters. It might stay with IDB. We'll need to talk about that with Theresa/Peggy/Ellen and see what they think. Might be a WIG decision.

**Comment by fureigh** [comment]
@RPentola Great questions. We can assign different permissions to different roles. What (if anything) are webmasters able to do that editors can't?

**Comment by RPentola** [comment]
@fureigh At this point I think that an editor could do anything an author could. 

So you could structure it pretty simply with an author doing x, y, z and an editor having privileges to do x, y, z, and a, b, c

**Comment by fureigh** [comment]
@rpentola What should the values of a, b and c be?

And is there anything webmasters can do that editors can’t?

**Comment by RPentola** [comment]
@fureigh OK, I'm going to SWAG it for now:
1) webmasters do not do anything an editor can't
2) webmasters need to: create, edit, delete (an unpublished article or piece of content)
3) editors need to: create, edit, delete (published or unpublished content), approve, deny, publish

Does that work for now? We can/should refine further as we go into actual user testing.

**Comment by fureigh** [comment]
@RPentola Yep, that works for now! Thanks. :)

**Comment by fureigh** [comment]
This is complete.
