### ISSUE TITLE
If testing video uploads, configure Drupal site to allow Brightcove connections 

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#76]
## User story
As a user researcher, *if* asking users to upload video files, I want the Drupal prototype to be accessible from the internet so that Brightcove can receive the uploaded files. (See technical note below.) 
  
## Acceptance criteria
- [ ] A test user (with role `content editor`?) can successfully upload a video file to the Drupal prototype.

## Definition of done
(See 'acceptance criteria'.)

## Technical notes
From https://www.drupal.org/project/brightcove:
> For uploading to work with versions 8.x-1.x and 7.x-6.x, your Drupal site needs to be accessible from the internet (public IP address or port-forwarding enabled) because Brightcove will need to fetch all uploaded video/image/caption files from your Drupal site. You should also configure PHP+apache to allow larger file uploads (default is 2MB).

## Other notes
Before starting work on this ticket, confirm — in https://github.com/18F/nsf/issues/70 or otherwise — that we actually need to test video upload functionality, not just video embedding.

**Comment by OpenGlobe** [comment]
Closing this in deference to #78
