### ISSUE TITLE
As a content editor, I want to be able to add videos from Brightcove.

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#78]
## User story
As a content editor, I want to be able to add videos from Brightcove so that I can make good use of existing workflows and resources.

From #70.
  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

## Outstanding questions
- [x] For this phase, do users need to be able to upload videos *to* Brightcove as well, or just add videos *from* Brightcove?
- [x] Which users should be able to do this? All content editors and admins?
- [x] @fureigh may need to request credentials in order to complete integration.

**Comment by fureigh** [comment]
Answers from this afternoon's conversation:

- Users just need to be able to add videos *from* Brightcove, not upload videos *to* Brightcove via this site.
- Example in lieu of credentials:

```
<iframe src="//players.brightcove.net/679256133001/default_default/index.html?videoId=4805848656001" 
allowfullscreen 
webkitallowfullscreen 
mozallowfullscreen 
width="428.57" 
height="150"></iframe>
```

**Comment by RPentola** [comment]
pasting in my email comment from this morning. This is an area where we should definitely do user testing.

<email>
Many of the webmasters outside of OLPA are not code-first users, so we should explore a solution that allows a drag/drop approach to adding videos. (Rather than pasting and customizing the code in the page.)

I see that Drupal has integration with Brightcove through the media module. (https://www.drupal.org/project/media). Would this module provide a more content-focused user experience (as opposed to code-focused)? And is this something you are working on for the prototype?
</email>

**Comment by fureigh** [comment]
@RPentola Yep, we'll definitely want to test this! I've started configuring the [Brightcove module](https://drupal.org/project/brightcove) for the prototype, since you mentioned Brightcove integration in #70.

I want to be sure I understand: when you say drag-and-drop, do you mean dragging from Brightcove (in a browser window) to the Drupal site (in another browser window or tab)?

**Comment by RPentola** [comment]
drag & drop or WYSIWYG. The concept would be that a user would see a list of videos and be able to pick which one to use. Then the video would display in the page. 

Video display: maybe not in-line with the text, but in a designated spot?  I'm not sure how the module works, so I'm flying blind on this one.

**Comment by fureigh** [comment]
Hmm — dragging and dropping a file that exists on one's own computer is supported, but dragging and dropping videos already uploaded to Brightcove would require significant customization and/or creating a new module. Let's circle back to this once we've given the out-of-the-box implementation a spin.

In the meantime, I'll need the following information to be able to finish configuring the out-of-the-box implementation:

![brightcove-config](https://user-images.githubusercontent.com/1244599/34056964-f77809f0-e189-11e7-8f8f-309fbf783459.png)


Who would have that information? (I strongly recommend sharing the answers via a tool like [fugacio.us](https://fugacio.us) or over a phone call, as email isn't secure.)

**Comment by RPentola** [comment]
@fureigh Yes--let's go with the regular OOTB version to start.

I think Ellen Weir would have those answers about Brightcove. @EYWeir (Is this your notation, Ellen?)

**Comment by fureigh** [comment]
Phone call scheduled for tomorrow morning. Thanks!

**Comment by RPentola** [comment]
@fureigh what time is the call? Could I participate, too?

**Comment by fureigh** [comment]
@RPentola I started my day early to have the call, so am just seeing this now — pardon.

The purpose of the call was to confirm 1) the list of needed credentials from the screenshot above and 2) how David will send them. Both of those are on track. If you had additional aims, let me know and we can figure out how best to achieve them. Thanks!

**Comment by fureigh** [comment]
This one has turned out to be a surprisingly heavy lift, but it's now ready for a look on dev-nsf (not yet on test-nsf). You should see a Brightcove icon next to the image icon in the WYSIWYG editor.

**Comment by fureigh** [comment]
@RPentola says 👍 (Slack)

**Comment by fureigh** [comment]
(Reopening 'til it's up on live)

**Comment by fureigh** [comment]
Confirming: this is up on live and the latest videos have been imported.
