### ISSUE TITLE
As an NSF administrator, I want to shadow the CMS implementation so that I can learn as the prototype is developed further. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#79]
## User story
As an NSF administrator, I want to shadow the CMS implementation so that I can learn as the prototype is developed further. 

This is dependent on task #69 

## Acceptance criteria
- [x] A date is selected for ongoing pairing opportunities with Theresa's team. 

## Definition of done
- [x] Calendar invitation is sent for agreed-to dates.

**Comment by fureigh** [comment]
This is mostly a process issue. Now that I'm not primarily focusing on deployment, we've set up a time for pairing tomorrow. We can schedule more after that point.
