### ISSUE TITLE
As a team member, I want to understand how work moves between UX/content > visual design > front end dev for a sprint cycle. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#8]
## User story
As a team member, I want to understand how work moves between UX/content > visual design > front end dev for a sprint cycle. 

## Acceptance criteria
- [x] A cadence of moving items ready for review between UX/content > visual design > front end dev is identified and documented
- [x] The flow is presented to the team for review
- [x] The team suggests any modifications and they are made

## Definition of done
- [x] The team has agreed to the cadence
- [ ] The cadence has been documented on the NSF wiki.

**Comment by austinhernandez** [comment]
## Rough draft proposal of work flow
To avoid duplicative work, I propose the whole team work in collaborative [design sprints]( http://www.uxbooth.com/articles/every-week-is-a-design-sprint/). To accommodate remote working and time zone overlap, I would suggest two week vs one week sprints. 
- The first 3 weeks are discovery
  - Design and Dev teams works together closely with the client, research, and strategy to understand issues and brainstorm on how to solve them. 
- The next 2 sprints (4 weeks) will be frequent cross-team collaboration and pairing, to create quick Sketch prototypes (based on the USWDS patterns), to validate hypotheses established in the discovery sprints.
  - This phase will be higher iteration, so to reduce iterations in development @line47 will assist in technical feasibility and interaction design suggestions while creating a framework in Federalist
 - Scott will then slowly start building out the functionality we've validated
- The following 3 sprints we will be moving from Sketch prototypes to HTML prototypes with assistance from visual design.
  - Austin (_that's me!_) will do design reviews and suggest feedback in HTML prototypes while developing, maintaining, and extending NSF patterns.
- The last sprints we will try to focus on a deliverable 
 - Design will make less risky assumptions to try and narrow down the scope of a deliverable 
- The last sprint would be execution of this deliverable ⬆️ 
- To note: There are 3 federal holidays in this time (Labor Day, Columbus Day, and Veteran's Day) 

## Principle (but extended over 2 weeks)
![cadence](https://user-images.githubusercontent.com/23194720/29037632-64ae08e0-7b72-11e7-9432-1433f939de82.png)

## Calendar
![sprint proposal-aug](https://user-images.githubusercontent.com/23194720/29037951-bd4ad7de-7b73-11e7-955a-bfdf7d4e7459.png)
![sprint proposal-sept](https://user-images.githubusercontent.com/23194720/29037954-be49ade0-7b73-11e7-8f8b-07a5d1014f9b.png)
![sprint proposal-oct](https://user-images.githubusercontent.com/23194720/29037957-c1878a72-7b73-11e7-82e3-ad8d87df15c6.png)
![sprint proposal-nov](https://user-images.githubusercontent.com/23194720/29037959-c4d0664a-7b73-11e7-9d78-d099b46dd042.png)

Let's discuss and improve!

**Comment by austinhernandez** [comment]
notes from our meeting: https://docs.google.com/document/d/1FTQ9UpuycI-8mU_fL_VmreXRFloSuNAe2mWQyL5DEJw/edit

@coreycaitlin is also working on integrating client meetings and how to incorporate the NSF team in our availability doc
