### ISSUE TITLE
As a team member, I want to understand how the document library on the current NSF site might translate to a CMS so I can know how to proceed (technically and/or to inform the acquisition).

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#81]
@peggyatnsf noted [in Slack](https://gsa-tts.slack.com/archives/C4AT9KJ5U/p1512740621000247):
> At the last workshop, the question came up about how the document library on the current NSF site might translate to a CMS, but we didn't have a chance to discuss the issue. Is there any general guidance you have about this? My main question is what, if anything, would in make sense to store in the CMS, the document files and the metadata, just the metadata (as is done now), or neither of these (it should remain a separate system).

To which I asked:
> Remind me of the approximate number of documents, what kinds of documents they are, and where they’re currently stored?
> 
> It’s generally best to minimize the number of steps it takes for someone to do what they need to do. So if it’s reasonably feasible to set things up such that users don’t have to switch between systems, that’s usually preferable.
> 
> Everything has its tradeoffs, though, so I’ll be interested to hear your answers to the above questions.

And Peggy replied:
> There are almost 9000 documents. Some are archived and perhaps could be deleted. They are reports, letters to the research community, documents announcing grant opportunities (which should probably not be included in this list but will need to be linked from the funding area of the site), newsletters, policies, etc. You can see the complete list on the bottom left of https://www.nsf.gov/publications/ods/.
> 
> The files are currently stored in the docroot for the site just like manually created HTML files are.

**Comment by peggyatnsf** [comment]
I'd still like to have a discussion around this unless it's been covered with others at NSF.

**Comment by OpenGlobe** [comment]
Sounds good!
