### ISSUE TITLE
As a developer, I want the subdomain beta.nsf.gov to be set up such/so that I can deploy a beta site to it.

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#82]
## User story
As a developer, I want the subdomain `beta.nsf.gov` to be set up such/so that I can deploy a beta site to it.

As an NSF team member, I want the subdomain `beta.nsf.gov` to be approved and "ready" so I can feel confident that when the time comes, it'll be possible to have a beta site there.
  
## Acceptance criteria
- [x] We have the necessary approval(s) to use the subdomain `beta.nsf.gov`.
- [x] The subdomain `beta.nsf.gov` has been created.
- [x] The next/remaining steps for deployment have been identified.

**Comment by OpenGlobe** [comment]
Update here - @trinehar is requesting the establishment of the domain via NSF channels.

**Comment by fureigh** [comment]
Great. This documentation will likely be relevant: https://cloud.gov/docs/apps/custom-domains/

**Comment by fureigh** [comment]
@trinehar, has there been any news on this?

**Comment by mtboesch** [comment]
My understanding based on https://cloud.gov/docs/apps/custom-domains/ and https://cloud.gov/docs/services/cdn-route/ is that the app needs to be setup on cloud.gov and a CDN service needs to be setup for the application on cloud.gov before the CNAME record can be configured in the NSF DNS.  According to the NSF infrastructure team, the creation of the beta.nsf.gov DNS is trivial and they are waiting on us to provide them the value to put in for the CNAME.

**Comment by OpenGlobe** [comment]
We have put in the request to move to a FISMA-low package (related).

**Comment by OpenGlobe** [comment]
Related: #152 (closed).
