### ISSUE TITLE
As a user researcher, I want to begin drafting a research plan so that I can begin recruiting participants.

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#9]
## User story
As a user researcher, I want to begin drafting a research plan so that I can begin recruiting participants.
  
## Acceptance criteria
- [x] Develop shell / template for research plan
- [x] Start a plan for remote gathering of user vision from OLPA/etc (and back-up plan for asynchronous remote
- [x] Gather user-independent tactics for research plan
- [x] Document tactics in the draft plan
- [x] Distribute the plan to the team for comment
- [x] Get alignment on user groups - keystone activity for starting recruitment; Identify groups, channels for outreach to people unfamiliar with NSF

## Definition of done
- [x] Plan has been distributed for comment to 18F team
- [x] Plan has been distributed to NSF for comment
- [x] Plan accepted by 18F and NSF
- [x] Document is exists in the team folder
- [x] Next steps have been identified

**Comment by coreycaitlin** [comment]
This is dependent on #10

**Comment by kategarklavs** [comment]
Howdy all! Starting to revise/modify the template research plan (borrowed from NASA). Stay tuned 📺

**Comment by OpenGlobe** [comment]
Hey all - should we break this into two separate cards - recruitment and development of the user research plan?

**Comment by onezerojeremy** [comment]
I vote yes!

**Comment by kategarklavs** [comment]
Howdy all! Just shared this in the channel, but here's a first pass at a plan/script:

https://docs.google.com/a/gsa.gov/document/d/1EDfOReiys296Jl4A_4izO-wyhZXd7UThg6N2-8sMkTw/edit?usp=sharing

This is a first draft, so please edit away! There are some bits that could use additional clarity (and some sections, such as prototype-related questions, that I can refine once we create prototypes).

cc @OpenGlobe @onezerojeremy @coreycaitlin

**Comment by OpenGlobe** [comment]
Related: #19, #25

**Comment by kategarklavs** [comment]
Update! I've incorporated @OpenGlobe and @onezerojeremy's suggestions (and thank you both for the excellent/quick feedback). @onezerojeremy is going to create a separate doc for the interview scripts.

**Comment by OpenGlobe** [comment]
Just waiting on NSF feedback before we can close.

**Comment by OpenGlobe** [comment]
@onezerojeremy did we need to do anything further re: NSF feedback here?  I want to just make sure we've accounted for any feedback we had received to date.

**Comment by onezerojeremy** [comment]
I believe we incorporated all we heard- I'll take a swing through the doc
tomorrow to verify and update the issue accordingly.
