### ISSUE TITLE
Some file triggers error/validation message for Alternate text

### ISSUE THREAD

**Issue by mtboesch** [18F/nsf#91]
## Steps to reproduce:
1. Log in
2. Click the Add content link in the Tools menu.
3. Click News
4. Fill in sample content.
5. Add the attached purplecellsbig.jpg and add Alernate text as "purple cells" without the quotes
6. Save as ready for review.
## Expected behavior:
The newly created content saves without errors.
## Actual behavior:
An error message displays the following for Alternative text, "This value should be of the correct primitive type. "
![purplecellsbig](https://user-images.githubusercontent.com/31212633/34895916-aed41120-f7b5-11e7-8aec-05abe3485491.jpg)

**Comment by fureigh** [comment]
Notes in progress:
* Check whether this has been discussed in the core Drupal issue queue.
* https://www.drupal.org/forum/support/post-installation/2017-09-28/this-value-should-be-of-the-correct-primitive-type
* https://www.drupal.org/project/svg_image/issues/2907492
* https://www.drupal.org/files/issues/fix_svg_default_size-2907492-3.patch (written to be SVG-specific, but look into it further)
