### ISSUE TITLE
As a user researcher, I want the WIG prototype so that I can finalize the second task script. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#94]
## User story
As a user researcher, I want the WIG prototype so that I can finalize the second task script. 

## Acceptance criteria
- [ ] We have the ePub workflow in-hand, and
- [ ] can design the second workflow. 

## Definition of done
- [ ] WIG workflow is working on prototype.

**Comment by RPentola** [comment]
This is complete and scripts are written. closing ticket
