### ISSUE TITLE
Successful deployment of CMS on cloud.gov, included environments are established. 

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#95]
## User story
As an engineer seeking to deploy a publicly accessible beta, I want to be able to deploy the beta's codebase to cloud.gov so that the ATO process will potentially be simpler.

By the end of this sprint, we would like a successful deployment of CMS on cloud.gov and identify the environments that we will have on cloud.gov (dev, staging, production for example)

## Acceptance criteria
- [x] The beta is up on cloud.gov. (Password-protected, I assume.)
- [x] Environments are established. 
- [x] Square away Cloud.gov deployment workflow 

Follow-up on https://github.com/18F/nsf/issues/69.

**Comment by mtboesch** [comment]
Do we know how many environments we will have on cloud.gov?  Development, staging and production for example?

**Comment by OpenGlobe** [comment]
Issue updated per sprint planning.

**Comment by OpenGlobe** [comment]
Related #141

**Comment by mtboesch** [comment]
What is the URL of the deployed application on cloud.gov?  Will NSF users be granted access to the spaces on cloud.gov?  Right now when I go to nsf-prototyping organization on cloud.gov, I see the following message.

You don’t have permission to see the spaces in this organization.
Organization auditors and billing managers can’t view spaces. Ask your organization’s administrator to give you these permissions..
