### ISSUE TITLE
As a team member I want to meet with DIS / cloud.gov so I can determine the requirements for the beta.nsf.gov ATO

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#96]
## User story
As a team member I want to meet with DIS / cloud.gov so I can determine the requirements for the beta.nsf.gov ATO

**Comment by fureigh** [comment]
@OpenGlobe I believe the ATO conversation on 1/19 covered this. Is there more to do before this ticket is considered complete?

**Comment by mtboesch** [comment]
I think there may be additional meetings based on the pending results from the action items of teh 1/19 meeting, so leaving this open for right now.

**Comment by OpenGlobe** [comment]
I think we have an issue open that covers this - merging with https://github.com/18F/nsf/issues/124
