### ISSUE TITLE
Content moderation transitions should change publication status

### ISSUE THREAD

**Issue by fureigh** [18F/nsf#97]
## User story
As a content editor or admin, I want content moderation transitions to immediately affect publication status so that the workflow states' effects match what you'd expect. 
  
## Acceptance criteria
- [ ] If content has `Draft` or `Ready for Review` status, changing it to `Published` status publishes it.
- [ ] If content has `Published` status, pulling it back into `Draft` or `Ready for Review` status unpublishes it.
- [ ] Any content with `Draft` or `Ready for Review` status is unpublished.
- [ ] Any content with `Published` status is published.

And come to think of it: we should probably call that state `Approved` instead of `Published`, because it's possible for content to be approved but not scheduled for publication until a later date.

**Comment by trinehar** [comment]
Also note that currently, editing a news story after publishing does not unpublish or remove it from the site. The previous content is simply replaced when the updated version is approved.

To remove a news item (or event /discovery etc) on the current site, the story is opened to editing, a "do not display on any site" flag is checked, and the item is republished.

**Comment by fureigh** [comment]
@trinehar Thanks for these notes!

Can you tell me a little more about how republication works on NSF's current site? If a story's been opened to editing, is it automatically unpublished until it's gone through a new approval process? Or does the old version stay up while the new one's being approved? Or...?

**Comment by fureigh** [comment]
Ah, and to make sure we're (literally) on the same page: does "currently" refer to the prototype-in-progress or to NSF's current site?

**Comment by trinehar** [comment]
Currently = behavior on current nsf site. Once published, the only way to remove an item from appearing on nsf.gov is to edit it, check the "do not display on any site" check box, and republish. It is not removed from the site until the republish action is completed. Simply reopening to edit does not affect the published content at all.

**Comment by trinehar** [comment]
Need to confirm with OLPA, but I think they mostly like being able to update a news item without affecting the current site, since links may have been emailed already, etc. Exception would be in the case of an egregiously bad error when they would rather just have the story offline until corrected.
